#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


: "${APP_HOME:?APP_HOME is not set}"

python $APP_HOME/manage.py collectstatic --noinput
{% if cookiecutter.use_whitenoise == 'y' and cookiecutter.frontend_pipeline == 'Django Compressor' %}
compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python $APP_HOME/manage.py compress
fi
{%- endif %}
{%- if cookiecutter.use_async == 'y' %}
exec gunicorn config.asgi $APP_HOME/gunicorn.conf.py --chdir=$APP_HOME -k uvicorn_worker.UvicornWorker
{%- else %}
exec gunicorn config.wsgi $APP_HOME/gunicorn.conf.py --chdir=$APP_HOME
{%- endif %}
