#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


: "${APP_HOME:?APP_HOME is not set}"

python $APP_HOME/manage.py collectstatic --noinput
{%- if cookiecutter.use_async == 'y' %}
exec gunicorn config.asgi $APP_HOME/gunicorn.conf.py --chdir=$APP_HOME -k uvicorn_worker.UvicornWorker
{%- else %}
exec gunicorn config.wsgi $APP_HOME/gunicorn.conf.py --chdir=$APP_HOME
{%- endif %}
